# Generated by Django 5.2.6 on 2025-11-03 10:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unsafe_ingredients', models.JSONField(default=list)),
                ('health_conditions', models.JSONField(default=list)),
                ('identified_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('product_category', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ocr_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ocr.ocrresult')),
            ],
        ),
    ]
